
#ifndef HW3WET_TYPES_AND_DEFINES_H
#define HW3WET_TYPES_AND_DEFINES_H

typedef enum  {
    COMPANY_SUCCESS,
    COMPANY_NULL_ARGUMENT,
    COMPANY_OUT_OF_MEMORY,
    COMPANY_INVALID_ARGUMENT,
    COMPANY_ID_ALREADY_EXIST,
    COMPANY_ID_DOES_NOT_EXIST,
} CompanyError;






#endif //HW3WET_TYPES_AND_DEFINES_H
